version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    assignees:
      - 'Zac-Zajdel'
    labels:
      - 'dependencies'
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
    assignees:
      - 'Zac-Zajdel'
    labels:
      - 'dependencies'
